name: Build Info
description: Record build info
outputs:
  build-info:
    description: Build info
    value: ${{ steps.build-info-builder.outputs.BUILDINFO }}
runs:
  using: composite
  steps:
    - id: build-info-builder
      shell: bash
      run: |
        ./.github/actions/build-info.sh "${{ github.workflow }}" "${{ github.run_number }}" > build-info.txt

name: Upload
description: Upload artifact
inputs:
  artifact:
    description: Artifact to upload
    required: true
  upload-host:
    description: Host to upload to
    required: true
  upload-path:
    description: Path on host to upload to
    required: true
runs:
  using: composite
  steps:
    - name: Upload
      run: rsync 
      shell: bash
