name: Build Info
description: Record build info
outputs:
  build-info:
    description: Build info
    value: ${{ steps.build-info-builder.outputs.BUILDINFO }}
runs:
  using: composite
  steps:
    - id: build-info-builder
      shell: bash
      run: |
        ./.github/actions/build-info.sh "${{ github.workflow }}" "${{ github.run_number }}" > build-info.txt
#        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
#        echo "BUILDINFO<<$EOF" >> $GITHUB_OUTPUT
#        echo -e "Source: $(git describe 2> /dev/null || git rev-parse --short HEAD)\nJob: ${{ github.workflow }}\nBuild #: ${{ github.run_number }}\nTime: $(printf '%(%Y-%m-%d %H:%M:%S)T\n')" >> $GITHUB_OUTPUT
#        #./.github/actions/build-info.sh >> $GITHUB_OUTPUT
#        echo "$EOF" >> $GITHUB_OUTPUT
