name: Hello world

on:
  workflow_dispatch:
    inputs:
      deploy-branch:
        description: Branch to upload
      deploy-host:
        description: Host to upload to
        default: connect7.chartiq.com
        required: true
      deploy-path:
        description: Path on remote host to upload to
        required: true
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world
        run: ./test.sh
      - name: Save file
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: test.out
  read-artifact:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Load file
        uses: actions/download-artifact@v3
        with:
          name: test-artifact
          path: .
      - name: Read file
        run: cat test.out
      - name: Test
        run: |
          whoami
          groups
          pwd
          mkdir -p ~/.ssh
          echo supersecretkey > ~/.ssh/id_rsa
          ls -lah ~/.ssh
  build-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build info
        id: build-info
        uses: ./.github/actions/build-info
      - name: Save build info
        uses: actions/upload-artifact@v3
        with:
          name: build-info
          path: build-info.txt

        #  upload-artifact:
        #    needs: setup
        #    runs-on: ubuntu-latest
        #    steps:
        #      - name: Checkout
        #        uses: actions/checkout@v3
        #      - name: Upload
        #        uses: ./.github/actions/upload.yml
