name: Hello world

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world
        run: ./test.sh
      - name: 1
        run: pwd
      - name: 2
        run: ls -lah